ghost:
    image: ghost:latest
    volumes:
        - ./tmp:/var/lib/ghost
        - ./config.js:/usr/src/ghost/config.js:ro
    ports:
        - "8000:2368"
    command: "node index"
    environment:
        NODE_ENV: development
