ghost:
    image: ghost:0.10.1
    volumes:
        - ./tmp:/var/lib/ghost
        # - ./config.js:/var/lib/ghost/config.js
    ports:
        - "8000:8000"
    environment:
        NODE_ENV: development
